CREATE TABLE IF NOT EXISTS deaths (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day INTEGER NOT NULL,
  name TEXT NOT NULL,
  meaning TEXT NOT NULL DEFAULT '',
  days INTEGER NOT NULL DEFAULT 0,
  epitaph TEXT NOT NULL DEFAULT '',
  site TEXT NOT NULL DEFAULT '',
  relics TEXT NOT NULL DEFAULT '[]',
  finished INTEGER NOT NULL DEFAULT 0,
  journey TEXT NOT NULL DEFAULT '[]',
  ts TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day INTEGER NOT NULL,
  text TEXT NOT NULL,
  ts TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ratelimit (
  ip TEXT NOT NULL,
  win INTEGER NOT NULL,
  n INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (ip, win)
);

CREATE INDEX IF NOT EXISTS deaths_day_rank ON deaths(day, days DESC, ts ASC);
CREATE INDEX IF NOT EXISTS deaths_site ON deaths(site);
CREATE INDEX IF NOT EXISTS deeds_day_ts ON deeds(day, ts DESC);
